---
commonOverlays: []
yamlFiles:
  - name: "postgres operator configmap"
    path: "../../vendor/configmap.yaml"
    outputPath: "database/zalando-postgres/config.yaml"
    overlays:
      - name: "ensure namespace is updated"
        query: metadata.namespace
        value: "{{ .namespace }}"
        onMissing:
          action: inject

